### DISCUSSION TITLE
Using with split configuration

### DISCUSSION THREAD

**Discussion by TScalzott** [Chouffy/home_assistant_tgtg#128] [Q&A] [answered]
I'm using split configuration for configuration.yaml.  For instance, I have a sensors folder and configuration.yaml contains this line:
   sensor: !include_dir_merge_list sensors/

I've installed home_assistant_tgtg via HACS and created a tgtg.yaml file in the sensors folder which follows this format:

```
 - platform: tgtg
   email: "my-email"
   access_token: "accesstoken"
   refresh_token: "refreshtoken"
   user_id: "myuserid"
   cookie: "datadome=..."
   scan_interval: 900
   item:

```
I can't for the life of me figure out how to get the tgtg integration to work with this.  It's installed but does not appear under Settings-->Integrations and I have no available entities.   It's definitely parsing the yaml and I have nothing of interest in the logs, other than to mention that the tgtg integration has not been tested--the same warning that we all get for lots of things like HACS itself.

Can anyone help guide me?   TIA!
