### DISCUSSION TITLE
Dashboard card example problem

### DISCUSSION THREAD

**Discussion by DaaShamy** [Chouffy/home_assistant_tgtg#130] [General]
Hi,
i'm using this integration and everything works fine. 
I see the entities and the notification works well, but the dashboard card example drives me crazy...

There's always this error:
Invalid entity ID at position 0: {'entity':

The template also works fine (tested with the dev-tools). It must be something with auto-entities + multiple-entity-row

Can someone help me out?

**Comment by ThanhCN0** [comment]
got the same errors and found that removing the variable assignments made it work for me but I have no idea why
```yaml
type: custom:auto-entities
card:
  type: entities
  title: TGTG Surprise Bags
filter:
  template: |-
    {% for state in states.sensor if 'sensor.tgtg_' in state.entity_id %}
      {%- if is_number(states(state.entity_id)) and states(state.entity_id) | int > 0 -%}
        {%- if state_attr(state.entity_id, 'pickup_start') is not none -%}
            {{
              {
                'entity': state.entity_id,
                'name': state_attr(state.entity_id, 'friendly_name')[5:],
                'type': "custom:multiple-entity-row",
                'unit': false,
                'secondary_info': as_timestamp(state_attr(state.entity_id, 'pickup_start')) | timestamp_custom('Pick up on %m/%d between %H:%M and ', true) + as_timestamp(state_attr(state.entity_id, 'pickup_end')) | timestamp_custom('%H:%M, $', true) + state_attr(state.entity_id, 'item_price')[:-3],
                'tap_action': {
                  'action': 'url',
                  'url_path': state_attr(state.entity_id, 'item_url')
                }
              }
            }},
        {%- endif -%}
      {%- endif -%}
    {% endfor %}
````
