### DISCUSSION TITLE
Notification Template

### DISCUSSION THREAD

**Discussion by wieluk** [Chouffy/home_assistant_tgtg#8] [Ideas]
I made this automation to notify me whenever a store I like has new items. I am just curious if you have a better way of doing it instead of listing all entity_id's. If not I just wanted to share because I would have liked a template :).

<details>
  <summary>simple yaml for notification</summary>
 
```yaml
alias: tgtg notify
trigger:
  - platform: state
    entity_id:
      - sensor.long
      - sensor.list
      - sensor.of
      - sensor.all
      - sensor.tgtg
      - sensor.stores

condition:
  #send notification only if stock changes from (0 or unavailable) to >=1
  - condition: template
    value_template: >-
      {{ trigger.to_state.state | float >= 1  and (trigger.from_state.state |
      float == 0 or trigger.from_state.state == "unavailable" )}}

action:
  #change notification method
  - service: notify.mobile_app_iphone
    data_template:
      message: '''{{ trigger.from_state.attributes.friendly_name }}'''
mode: parallel
max: 10
```
  
</details>

<details>
  <summary>Iphone with deleting messages</summary>

This one is for Iphone if you want to delete messages if stock is back to 0

```yaml
alias: tgtg notify
trigger:
  - platform: state
    entity_id:
      - sensor.long
      - sensor.list
      - sensor.of
      - sensor.all
      - sensor.tgtg
      - sensor.stores
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state | float >= 1 }}'
          - condition: template
            value_template: >-
              {{ trigger.from_state.state | float == 0 or
              trigger.from_state.state == "unavailable" }}
        sequence:
            #change notification method
          - service: notify.mobile_app_iphone
            data_template:
              message: '''{{ trigger.from_state.attributes.friendly_name }}'''
              data:
                tag: '''{{ trigger.from_state.attributes.friendly_name }}'''
    default: []

#delete notification if stock changes back to 0
  - choose: 
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state | float == 0 }}'
        sequence:
          - service: notify.mobile_app_iphone
            data:
              message: clear_notification
              data:
                tag: '''{{ trigger.from_state.attributes.friendly_name }}'''
    default: []
mode: parallel
max: 10
```
  
</details>

\
I changed to android and I  updated the yaml automation a little bit to also open the app tgtg app if i click on the notification.

<details>
  <summary>Android yaml</summary>
  

  
  ```yaml

alias: tgtg notify
description: ''
trigger:
  - platform: state
    entity_id:
      - sensor.long
      - sensor.list
      - sensor.of
      - sensor.all
      - sensor.tgtg
      - sensor.stores

#only trigger when I am in my hometown
condition:
  - condition: numeric_state
    entity_id: proximity.home
    below: '30000'

action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state | float >= 1 }}'
          - condition: template
            value_template: >-
              {{ trigger.from_state.state | float == 0 or
              trigger.from_state.state == "unavailable" }}
        sequence:
          - service: notify.mobile_app_android
            data:
              message: >-
                '''{{ trigger.to_state.attributes.friendly_name }} for {{
                trigger.to_state.attributes['TGTG Price'] }} between {{
                trigger.to_state.attributes['Pickup start'] |as_timestamp |
                timestamp_custom('%H:%M') }} and {{
                trigger.to_state.attributes['Pickup stop'] |as_timestamp |
                timestamp_custom('%H:%M on %d.%m.%y') }}'''
              data:
                tag: '''{{ trigger.to_state.attributes.friendly_name }}'''
                clickAction: '{{ trigger.to_state.attributes[''Item URL''] }}'
    default: []
  
- choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state | float == 0 }}'
        sequence:
          - service: notify.mobile_app_android
            data:
              message: clear_notification
              data:
                tag: '''{{ trigger.to_state.attributes.friendly_name }}'''
    default: []
mode: parallel
max: 25
```
  
</details>

**Comment by linux-guru-com** [comment]
@wieluk 
Thanks for the nice notification template.
Sorry to say, but there is a typo/syntax error in it (at the iPhone part).
After modifying it, the notification works great for me.
Sorry for the bad formatting. I don't know how to do it better without creating an issue for it.

```yml
alias: tgtg notify
trigger:
  - platform: state
    entity_id:
      - sensor.long
      - sensor.list
      - sensor.of
      - sensor.all
      - sensor.tgtg
      - sensor.stores
action:
  - choose:
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state | float >= 1 }}'
          - condition: template
            value_template: >-
              {{ trigger.from_state.state | float == 0 or
              trigger.from_state.state == "unavailable" }}
        sequence:
            #change notification method
          - service: notify.mobile_app_iphone
            data_template:
              message: '''{{ trigger.from_state.attributes.friendly_name }}'''
```
                  data:
```
                tag: '''{{ trigger.from_state.attributes.friendly_name }}'''
    default: []

#delete notification if stock changes back to 0
  - choose: 
      - conditions:
          - condition: template
            value_template: '{{ trigger.to_state.state | float == 0 }}'
        sequence:
          - service: notify.mobile_app_iphone
            data:
              message: clear_notification
              data:
                tag: '''{{ trigger.from_state.attributes.friendly_name }}'''
    default: []
mode: parallel
max: 10
```

**Comment by AtomikWiWa** [comment]
Hello all,
I am trying to use this setting for notifications, but I am getting the following error:

**Error: Error rendering data template: UndefinedError: 'dict object' has no attribute 'from_state'**

Does anyone know what can happen?

**Comment by wieluk** [comment]
@linux-guru-com  thanks i changed it in the post.
@AtomikWiWa I am not sure what the problem is. Did you use your tgtg sensors? 

I just saw the senors have new attributes like price and collection time. I will try to add these to the notification.

**Comment by frankm000** [comment]
anything new here? i tried troubleshooting this for couple of hours but didnt found the issue.

**Comment by wieluk** [comment]
For me it still works. What is your problem? What does not work?

**Comment by blowk** [comment]
Do you need to set all sensors
```
      - sensor.long
      - sensor.list
      - sensor.of
      - sensor.all
      - sensor.tgtg
      - sensor.stores
```

or only ?
` - sensor.tgtg`

**Reply by wieluk** [reply]
Yeah unfortunately every single sensor. When I tried sensor.tgtg* it did not work maybe they changed something about it

**Reply by blowk** [reply]
So the full code should be or do I need anythin else to make it work?

```
alias: tgtg notify
trigger:
  - platform: state
    entity_id:
      - sensor.tgtg_shop_one
      - sensor.tgtg_shop_two
      - sensor.tgtg_shop_three
      - sensor.tgtg_shop_four
      - sensor.tgtg_shop_five
      - sensor.tgtg_shop_six
    
#only trigger when I am in my hometown
condition:
- condition: numeric_state
  entity_id: proximity.home
  below: '30000'
  
action:
- choose:
    - conditions:
        - condition: template
          value_template: '{{ trigger.to_state.state | float >= 1 }}'
        - condition: template
          value_template: >-
            {{ trigger.from_state.state | float == 0 or
            trigger.from_state.state == "unavailable" }}
      sequence:
        - service: notify.mobile_app_android
          data:
            message: >-
              '''{{ trigger.to_state.attributes.friendly_name }} for {{
              trigger.to_state.attributes['TGTG Price'] }} between {{
              trigger.to_state.attributes['Pickup start'] |as_timestamp |
              timestamp_custom('%H:%M') }} and {{
              trigger.to_state.attributes['Pickup stop'] |as_timestamp |
              timestamp_custom('%H:%M on %d.%m.%y') }}'''
            data:
              tag: '''{{ trigger.to_state.attributes.friendly_name }}'''
              clickAction: '{{ trigger.to_state.attributes[''Item URL''] }}'
  default: []

- choose:
    - conditions:
        - condition: template
          value_template: '{{ trigger.to_state.state | float == 0 }}'
      sequence:
        - service: notify.mobile_app_android
          data:
            message: clear_notification
            data:
              tag: '''{{ trigger.to_state.attributes.friendly_name }}'''
  default: []
mode: parallel
max: 25
```
